name: Build

on: 
  push:
    branches: master
    paths-ignore: '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - run: dotnet build -c Release
